// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gy_home/internal/data/ent/plancategory"
	"gy_home/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlanCategoryUpdate is the builder for updating PlanCategory entities.
type PlanCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *PlanCategoryMutation
}

// Where appends a list predicates to the PlanCategoryUpdate builder.
func (pcu *PlanCategoryUpdate) Where(ps ...predicate.PlanCategory) *PlanCategoryUpdate {
	pcu.mutation.Where(ps...)
	return pcu
}

// SetSort sets the "sort" field.
func (pcu *PlanCategoryUpdate) SetSort(i int32) *PlanCategoryUpdate {
	pcu.mutation.ResetSort()
	pcu.mutation.SetSort(i)
	return pcu
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (pcu *PlanCategoryUpdate) SetNillableSort(i *int32) *PlanCategoryUpdate {
	if i != nil {
		pcu.SetSort(*i)
	}
	return pcu
}

// AddSort adds i to the "sort" field.
func (pcu *PlanCategoryUpdate) AddSort(i int32) *PlanCategoryUpdate {
	pcu.mutation.AddSort(i)
	return pcu
}

// SetName sets the "name" field.
func (pcu *PlanCategoryUpdate) SetName(s string) *PlanCategoryUpdate {
	pcu.mutation.SetName(s)
	return pcu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pcu *PlanCategoryUpdate) SetNillableName(s *string) *PlanCategoryUpdate {
	if s != nil {
		pcu.SetName(*s)
	}
	return pcu
}

// SetContent sets the "content" field.
func (pcu *PlanCategoryUpdate) SetContent(s string) *PlanCategoryUpdate {
	pcu.mutation.SetContent(s)
	return pcu
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (pcu *PlanCategoryUpdate) SetNillableContent(s *string) *PlanCategoryUpdate {
	if s != nil {
		pcu.SetContent(*s)
	}
	return pcu
}

// SetURL sets the "url" field.
func (pcu *PlanCategoryUpdate) SetURL(s string) *PlanCategoryUpdate {
	pcu.mutation.SetURL(s)
	return pcu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (pcu *PlanCategoryUpdate) SetNillableURL(s *string) *PlanCategoryUpdate {
	if s != nil {
		pcu.SetURL(*s)
	}
	return pcu
}

// Mutation returns the PlanCategoryMutation object of the builder.
func (pcu *PlanCategoryUpdate) Mutation() *PlanCategoryMutation {
	return pcu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pcu *PlanCategoryUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pcu.hooks) == 0 {
		affected, err = pcu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PlanCategoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pcu.mutation = mutation
			affected, err = pcu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pcu.hooks) - 1; i >= 0; i-- {
			if pcu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pcu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pcu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pcu *PlanCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := pcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pcu *PlanCategoryUpdate) Exec(ctx context.Context) error {
	_, err := pcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcu *PlanCategoryUpdate) ExecX(ctx context.Context) {
	if err := pcu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pcu *PlanCategoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   plancategory.Table,
			Columns: plancategory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: plancategory.FieldID,
			},
		},
	}
	if ps := pcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pcu.mutation.Sort(); ok {
		_spec.SetField(plancategory.FieldSort, field.TypeInt32, value)
	}
	if value, ok := pcu.mutation.AddedSort(); ok {
		_spec.AddField(plancategory.FieldSort, field.TypeInt32, value)
	}
	if value, ok := pcu.mutation.Name(); ok {
		_spec.SetField(plancategory.FieldName, field.TypeString, value)
	}
	if value, ok := pcu.mutation.Content(); ok {
		_spec.SetField(plancategory.FieldContent, field.TypeString, value)
	}
	if value, ok := pcu.mutation.URL(); ok {
		_spec.SetField(plancategory.FieldURL, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plancategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// PlanCategoryUpdateOne is the builder for updating a single PlanCategory entity.
type PlanCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlanCategoryMutation
}

// SetSort sets the "sort" field.
func (pcuo *PlanCategoryUpdateOne) SetSort(i int32) *PlanCategoryUpdateOne {
	pcuo.mutation.ResetSort()
	pcuo.mutation.SetSort(i)
	return pcuo
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (pcuo *PlanCategoryUpdateOne) SetNillableSort(i *int32) *PlanCategoryUpdateOne {
	if i != nil {
		pcuo.SetSort(*i)
	}
	return pcuo
}

// AddSort adds i to the "sort" field.
func (pcuo *PlanCategoryUpdateOne) AddSort(i int32) *PlanCategoryUpdateOne {
	pcuo.mutation.AddSort(i)
	return pcuo
}

// SetName sets the "name" field.
func (pcuo *PlanCategoryUpdateOne) SetName(s string) *PlanCategoryUpdateOne {
	pcuo.mutation.SetName(s)
	return pcuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pcuo *PlanCategoryUpdateOne) SetNillableName(s *string) *PlanCategoryUpdateOne {
	if s != nil {
		pcuo.SetName(*s)
	}
	return pcuo
}

// SetContent sets the "content" field.
func (pcuo *PlanCategoryUpdateOne) SetContent(s string) *PlanCategoryUpdateOne {
	pcuo.mutation.SetContent(s)
	return pcuo
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (pcuo *PlanCategoryUpdateOne) SetNillableContent(s *string) *PlanCategoryUpdateOne {
	if s != nil {
		pcuo.SetContent(*s)
	}
	return pcuo
}

// SetURL sets the "url" field.
func (pcuo *PlanCategoryUpdateOne) SetURL(s string) *PlanCategoryUpdateOne {
	pcuo.mutation.SetURL(s)
	return pcuo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (pcuo *PlanCategoryUpdateOne) SetNillableURL(s *string) *PlanCategoryUpdateOne {
	if s != nil {
		pcuo.SetURL(*s)
	}
	return pcuo
}

// Mutation returns the PlanCategoryMutation object of the builder.
func (pcuo *PlanCategoryUpdateOne) Mutation() *PlanCategoryMutation {
	return pcuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pcuo *PlanCategoryUpdateOne) Select(field string, fields ...string) *PlanCategoryUpdateOne {
	pcuo.fields = append([]string{field}, fields...)
	return pcuo
}

// Save executes the query and returns the updated PlanCategory entity.
func (pcuo *PlanCategoryUpdateOne) Save(ctx context.Context) (*PlanCategory, error) {
	var (
		err  error
		node *PlanCategory
	)
	if len(pcuo.hooks) == 0 {
		node, err = pcuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PlanCategoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pcuo.mutation = mutation
			node, err = pcuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pcuo.hooks) - 1; i >= 0; i-- {
			if pcuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pcuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pcuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PlanCategory)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PlanCategoryMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (pcuo *PlanCategoryUpdateOne) SaveX(ctx context.Context) *PlanCategory {
	node, err := pcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pcuo *PlanCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := pcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcuo *PlanCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := pcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pcuo *PlanCategoryUpdateOne) sqlSave(ctx context.Context) (_node *PlanCategory, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   plancategory.Table,
			Columns: plancategory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: plancategory.FieldID,
			},
		},
	}
	id, ok := pcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlanCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plancategory.FieldID)
		for _, f := range fields {
			if !plancategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != plancategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pcuo.mutation.Sort(); ok {
		_spec.SetField(plancategory.FieldSort, field.TypeInt32, value)
	}
	if value, ok := pcuo.mutation.AddedSort(); ok {
		_spec.AddField(plancategory.FieldSort, field.TypeInt32, value)
	}
	if value, ok := pcuo.mutation.Name(); ok {
		_spec.SetField(plancategory.FieldName, field.TypeString, value)
	}
	if value, ok := pcuo.mutation.Content(); ok {
		_spec.SetField(plancategory.FieldContent, field.TypeString, value)
	}
	if value, ok := pcuo.mutation.URL(); ok {
		_spec.SetField(plancategory.FieldURL, field.TypeString, value)
	}
	_node = &PlanCategory{config: pcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plancategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
