// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gy_home/internal/data/ent/plancategory"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlanCategoryCreate is the builder for creating a PlanCategory entity.
type PlanCategoryCreate struct {
	config
	mutation *PlanCategoryMutation
	hooks    []Hook
}

// SetSort sets the "sort" field.
func (pcc *PlanCategoryCreate) SetSort(i int32) *PlanCategoryCreate {
	pcc.mutation.SetSort(i)
	return pcc
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (pcc *PlanCategoryCreate) SetNillableSort(i *int32) *PlanCategoryCreate {
	if i != nil {
		pcc.SetSort(*i)
	}
	return pcc
}

// SetName sets the "name" field.
func (pcc *PlanCategoryCreate) SetName(s string) *PlanCategoryCreate {
	pcc.mutation.SetName(s)
	return pcc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pcc *PlanCategoryCreate) SetNillableName(s *string) *PlanCategoryCreate {
	if s != nil {
		pcc.SetName(*s)
	}
	return pcc
}

// SetContent sets the "content" field.
func (pcc *PlanCategoryCreate) SetContent(s string) *PlanCategoryCreate {
	pcc.mutation.SetContent(s)
	return pcc
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (pcc *PlanCategoryCreate) SetNillableContent(s *string) *PlanCategoryCreate {
	if s != nil {
		pcc.SetContent(*s)
	}
	return pcc
}

// SetURL sets the "url" field.
func (pcc *PlanCategoryCreate) SetURL(s string) *PlanCategoryCreate {
	pcc.mutation.SetURL(s)
	return pcc
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (pcc *PlanCategoryCreate) SetNillableURL(s *string) *PlanCategoryCreate {
	if s != nil {
		pcc.SetURL(*s)
	}
	return pcc
}

// SetID sets the "id" field.
func (pcc *PlanCategoryCreate) SetID(i int32) *PlanCategoryCreate {
	pcc.mutation.SetID(i)
	return pcc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pcc *PlanCategoryCreate) SetNillableID(i *int32) *PlanCategoryCreate {
	if i != nil {
		pcc.SetID(*i)
	}
	return pcc
}

// Mutation returns the PlanCategoryMutation object of the builder.
func (pcc *PlanCategoryCreate) Mutation() *PlanCategoryMutation {
	return pcc.mutation
}

// Save creates the PlanCategory in the database.
func (pcc *PlanCategoryCreate) Save(ctx context.Context) (*PlanCategory, error) {
	var (
		err  error
		node *PlanCategory
	)
	pcc.defaults()
	if len(pcc.hooks) == 0 {
		if err = pcc.check(); err != nil {
			return nil, err
		}
		node, err = pcc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PlanCategoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pcc.check(); err != nil {
				return nil, err
			}
			pcc.mutation = mutation
			if node, err = pcc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pcc.hooks) - 1; i >= 0; i-- {
			if pcc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pcc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pcc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PlanCategory)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PlanCategoryMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pcc *PlanCategoryCreate) SaveX(ctx context.Context) *PlanCategory {
	v, err := pcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcc *PlanCategoryCreate) Exec(ctx context.Context) error {
	_, err := pcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcc *PlanCategoryCreate) ExecX(ctx context.Context) {
	if err := pcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pcc *PlanCategoryCreate) defaults() {
	if _, ok := pcc.mutation.Sort(); !ok {
		v := plancategory.DefaultSort
		pcc.mutation.SetSort(v)
	}
	if _, ok := pcc.mutation.Name(); !ok {
		v := plancategory.DefaultName
		pcc.mutation.SetName(v)
	}
	if _, ok := pcc.mutation.Content(); !ok {
		v := plancategory.DefaultContent
		pcc.mutation.SetContent(v)
	}
	if _, ok := pcc.mutation.URL(); !ok {
		v := plancategory.DefaultURL
		pcc.mutation.SetURL(v)
	}
	if _, ok := pcc.mutation.ID(); !ok {
		v := plancategory.DefaultID
		pcc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pcc *PlanCategoryCreate) check() error {
	if _, ok := pcc.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "PlanCategory.sort"`)}
	}
	if _, ok := pcc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PlanCategory.name"`)}
	}
	if _, ok := pcc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "PlanCategory.content"`)}
	}
	if _, ok := pcc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "PlanCategory.url"`)}
	}
	return nil
}

func (pcc *PlanCategoryCreate) sqlSave(ctx context.Context) (*PlanCategory, error) {
	_node, _spec := pcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int32(id)
	}
	return _node, nil
}

func (pcc *PlanCategoryCreate) createSpec() (*PlanCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &PlanCategory{config: pcc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: plancategory.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: plancategory.FieldID,
			},
		}
	)
	if id, ok := pcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pcc.mutation.Sort(); ok {
		_spec.SetField(plancategory.FieldSort, field.TypeInt32, value)
		_node.Sort = value
	}
	if value, ok := pcc.mutation.Name(); ok {
		_spec.SetField(plancategory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pcc.mutation.Content(); ok {
		_spec.SetField(plancategory.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := pcc.mutation.URL(); ok {
		_spec.SetField(plancategory.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	return _node, _spec
}

// PlanCategoryCreateBulk is the builder for creating many PlanCategory entities in bulk.
type PlanCategoryCreateBulk struct {
	config
	builders []*PlanCategoryCreate
}

// Save creates the PlanCategory entities in the database.
func (pccb *PlanCategoryCreateBulk) Save(ctx context.Context) ([]*PlanCategory, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pccb.builders))
	nodes := make([]*PlanCategory, len(pccb.builders))
	mutators := make([]Mutator, len(pccb.builders))
	for i := range pccb.builders {
		func(i int, root context.Context) {
			builder := pccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlanCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pccb *PlanCategoryCreateBulk) SaveX(ctx context.Context) []*PlanCategory {
	v, err := pccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pccb *PlanCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := pccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pccb *PlanCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := pccb.Exec(ctx); err != nil {
		panic(err)
	}
}
