// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gy_home/internal/data/ent/banner"
	"gy_home/internal/data/ent/plan"
	"gy_home/internal/data/ent/plancategory"
	"gy_home/internal/data/ent/product"
	"gy_home/internal/data/ent/productcategory"
	"gy_home/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bannerFields := schema.Banner{}.Fields()
	_ = bannerFields
	// bannerDescURL is the schema descriptor for url field.
	bannerDescURL := bannerFields[0].Descriptor()
	// banner.DefaultURL holds the default value on creation for the url field.
	banner.DefaultURL = bannerDescURL.Default.(string)
	// bannerDescSort is the schema descriptor for sort field.
	bannerDescSort := bannerFields[2].Descriptor()
	// banner.DefaultSort holds the default value on creation for the sort field.
	banner.DefaultSort = bannerDescSort.Default.(int32)
	// bannerDescTitle is the schema descriptor for title field.
	bannerDescTitle := bannerFields[3].Descriptor()
	// banner.DefaultTitle holds the default value on creation for the title field.
	banner.DefaultTitle = bannerDescTitle.Default.(string)
	// bannerDescType is the schema descriptor for type field.
	bannerDescType := bannerFields[4].Descriptor()
	// banner.DefaultType holds the default value on creation for the type field.
	banner.DefaultType = bannerDescType.Default.(string)
	// bannerDescLinkID is the schema descriptor for link_id field.
	bannerDescLinkID := bannerFields[5].Descriptor()
	// banner.DefaultLinkID holds the default value on creation for the link_id field.
	banner.DefaultLinkID = bannerDescLinkID.Default.(string)
	// bannerDescStatus is the schema descriptor for status field.
	bannerDescStatus := bannerFields[6].Descriptor()
	// banner.DefaultStatus holds the default value on creation for the status field.
	banner.DefaultStatus = bannerDescStatus.Default.(int)
	// bannerDescID is the schema descriptor for id field.
	bannerDescID := bannerFields[1].Descriptor()
	// banner.DefaultID holds the default value on creation for the id field.
	banner.DefaultID = bannerDescID.Default.(int32)
	planFields := schema.Plan{}.Fields()
	_ = planFields
	// planDescRecommend is the schema descriptor for recommend field.
	planDescRecommend := planFields[0].Descriptor()
	// plan.DefaultRecommend holds the default value on creation for the recommend field.
	plan.DefaultRecommend = planDescRecommend.Default.(int)
	// planDescCategoryID is the schema descriptor for category_id field.
	planDescCategoryID := planFields[2].Descriptor()
	// plan.DefaultCategoryID holds the default value on creation for the category_id field.
	plan.DefaultCategoryID = planDescCategoryID.Default.(int32)
	// planDescCategory is the schema descriptor for category field.
	planDescCategory := planFields[3].Descriptor()
	// plan.DefaultCategory holds the default value on creation for the category field.
	plan.DefaultCategory = planDescCategory.Default.(string)
	// planDescName is the schema descriptor for name field.
	planDescName := planFields[4].Descriptor()
	// plan.DefaultName holds the default value on creation for the name field.
	plan.DefaultName = planDescName.Default.(string)
	// planDescURL is the schema descriptor for url field.
	planDescURL := planFields[5].Descriptor()
	// plan.DefaultURL holds the default value on creation for the url field.
	plan.DefaultURL = planDescURL.Default.(string)
	// planDescID is the schema descriptor for id field.
	planDescID := planFields[1].Descriptor()
	// plan.DefaultID holds the default value on creation for the id field.
	plan.DefaultID = planDescID.Default.(int32)
	plancategoryFields := schema.PlanCategory{}.Fields()
	_ = plancategoryFields
	// plancategoryDescSort is the schema descriptor for sort field.
	plancategoryDescSort := plancategoryFields[1].Descriptor()
	// plancategory.DefaultSort holds the default value on creation for the sort field.
	plancategory.DefaultSort = plancategoryDescSort.Default.(int32)
	// plancategoryDescName is the schema descriptor for name field.
	plancategoryDescName := plancategoryFields[2].Descriptor()
	// plancategory.DefaultName holds the default value on creation for the name field.
	plancategory.DefaultName = plancategoryDescName.Default.(string)
	// plancategoryDescContent is the schema descriptor for content field.
	plancategoryDescContent := plancategoryFields[3].Descriptor()
	// plancategory.DefaultContent holds the default value on creation for the content field.
	plancategory.DefaultContent = plancategoryDescContent.Default.(string)
	// plancategoryDescURL is the schema descriptor for url field.
	plancategoryDescURL := plancategoryFields[4].Descriptor()
	// plancategory.DefaultURL holds the default value on creation for the url field.
	plancategory.DefaultURL = plancategoryDescURL.Default.(string)
	// plancategoryDescID is the schema descriptor for id field.
	plancategoryDescID := plancategoryFields[0].Descriptor()
	// plancategory.DefaultID holds the default value on creation for the id field.
	plancategory.DefaultID = plancategoryDescID.Default.(int32)
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescStatus is the schema descriptor for status field.
	productDescStatus := productFields[0].Descriptor()
	// product.DefaultStatus holds the default value on creation for the status field.
	product.DefaultStatus = productDescStatus.Default.(int)
	// productDescRecommend is the schema descriptor for recommend field.
	productDescRecommend := productFields[1].Descriptor()
	// product.DefaultRecommend holds the default value on creation for the recommend field.
	product.DefaultRecommend = productDescRecommend.Default.(int)
	// productDescHistory is the schema descriptor for history field.
	productDescHistory := productFields[3].Descriptor()
	// product.DefaultHistory holds the default value on creation for the history field.
	product.DefaultHistory = productDescHistory.Default.(int32)
	// productDescCategoryID is the schema descriptor for category_id field.
	productDescCategoryID := productFields[4].Descriptor()
	// product.DefaultCategoryID holds the default value on creation for the category_id field.
	product.DefaultCategoryID = productDescCategoryID.Default.(int32)
	// productDescCategoryName is the schema descriptor for category_name field.
	productDescCategoryName := productFields[5].Descriptor()
	// product.DefaultCategoryName holds the default value on creation for the category_name field.
	product.DefaultCategoryName = productDescCategoryName.Default.(string)
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[6].Descriptor()
	// product.DefaultName holds the default value on creation for the name field.
	product.DefaultName = productDescName.Default.(string)
	// productDescContent is the schema descriptor for content field.
	productDescContent := productFields[7].Descriptor()
	// product.DefaultContent holds the default value on creation for the content field.
	product.DefaultContent = productDescContent.Default.(string)
	// productDescServiceLink is the schema descriptor for service_link field.
	productDescServiceLink := productFields[9].Descriptor()
	// product.DefaultServiceLink holds the default value on creation for the service_link field.
	product.DefaultServiceLink = productDescServiceLink.Default.(string)
	// productDescApplyLink is the schema descriptor for apply_link field.
	productDescApplyLink := productFields[10].Descriptor()
	// product.DefaultApplyLink holds the default value on creation for the apply_link field.
	product.DefaultApplyLink = productDescApplyLink.Default.(string)
	// productDescID is the schema descriptor for id field.
	productDescID := productFields[2].Descriptor()
	// product.DefaultID holds the default value on creation for the id field.
	product.DefaultID = productDescID.Default.(int32)
	productcategoryFields := schema.ProductCategory{}.Fields()
	_ = productcategoryFields
	// productcategoryDescStatus is the schema descriptor for status field.
	productcategoryDescStatus := productcategoryFields[0].Descriptor()
	// productcategory.DefaultStatus holds the default value on creation for the status field.
	productcategory.DefaultStatus = productcategoryDescStatus.Default.(int)
	// productcategoryDescLevel is the schema descriptor for level field.
	productcategoryDescLevel := productcategoryFields[2].Descriptor()
	// productcategory.DefaultLevel holds the default value on creation for the level field.
	productcategory.DefaultLevel = productcategoryDescLevel.Default.(int32)
	// productcategoryDescParentID is the schema descriptor for parent_id field.
	productcategoryDescParentID := productcategoryFields[3].Descriptor()
	// productcategory.DefaultParentID holds the default value on creation for the parent_id field.
	productcategory.DefaultParentID = productcategoryDescParentID.Default.(int32)
	// productcategoryDescSort is the schema descriptor for sort field.
	productcategoryDescSort := productcategoryFields[4].Descriptor()
	// productcategory.DefaultSort holds the default value on creation for the sort field.
	productcategory.DefaultSort = productcategoryDescSort.Default.(int32)
	// productcategoryDescName is the schema descriptor for name field.
	productcategoryDescName := productcategoryFields[5].Descriptor()
	// productcategory.DefaultName holds the default value on creation for the name field.
	productcategory.DefaultName = productcategoryDescName.Default.(string)
	// productcategoryDescID is the schema descriptor for id field.
	productcategoryDescID := productcategoryFields[1].Descriptor()
	// productcategory.DefaultID holds the default value on creation for the id field.
	productcategory.DefaultID = productcategoryDescID.Default.(int32)
}
