// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gy_home/internal/data/ent/predicate"
	"gy_home/internal/data/ent/site"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SiteUpdate is the builder for updating Site entities.
type SiteUpdate struct {
	config
	hooks    []Hook
	mutation *SiteMutation
}

// Where appends a list predicates to the SiteUpdate builder.
func (su *SiteUpdate) Where(ps ...predicate.Site) *SiteUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetSort sets the "sort" field.
func (su *SiteUpdate) SetSort(i int32) *SiteUpdate {
	su.mutation.ResetSort()
	su.mutation.SetSort(i)
	return su
}

// AddSort adds i to the "sort" field.
func (su *SiteUpdate) AddSort(i int32) *SiteUpdate {
	su.mutation.AddSort(i)
	return su
}

// SetStatus sets the "status" field.
func (su *SiteUpdate) SetStatus(i int) *SiteUpdate {
	su.mutation.ResetStatus()
	su.mutation.SetStatus(i)
	return su
}

// AddStatus adds i to the "status" field.
func (su *SiteUpdate) AddStatus(i int) *SiteUpdate {
	su.mutation.AddStatus(i)
	return su
}

// SetName sets the "name" field.
func (su *SiteUpdate) SetName(s string) *SiteUpdate {
	su.mutation.SetName(s)
	return su
}

// SetLink sets the "link" field.
func (su *SiteUpdate) SetLink(s string) *SiteUpdate {
	su.mutation.SetLink(s)
	return su
}

// SetCategory sets the "category" field.
func (su *SiteUpdate) SetCategory(s string) *SiteUpdate {
	su.mutation.SetCategory(s)
	return su
}

// Mutation returns the SiteMutation object of the builder.
func (su *SiteUpdate) Mutation() *SiteMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SiteUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SiteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SiteUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SiteUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SiteUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SiteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   site.Table,
			Columns: site.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: site.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Sort(); ok {
		_spec.SetField(site.FieldSort, field.TypeInt32, value)
	}
	if value, ok := su.mutation.AddedSort(); ok {
		_spec.AddField(site.FieldSort, field.TypeInt32, value)
	}
	if value, ok := su.mutation.Status(); ok {
		_spec.SetField(site.FieldStatus, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedStatus(); ok {
		_spec.AddField(site.FieldStatus, field.TypeInt, value)
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(site.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.Link(); ok {
		_spec.SetField(site.FieldLink, field.TypeString, value)
	}
	if value, ok := su.mutation.Category(); ok {
		_spec.SetField(site.FieldCategory, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// SiteUpdateOne is the builder for updating a single Site entity.
type SiteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SiteMutation
}

// SetSort sets the "sort" field.
func (suo *SiteUpdateOne) SetSort(i int32) *SiteUpdateOne {
	suo.mutation.ResetSort()
	suo.mutation.SetSort(i)
	return suo
}

// AddSort adds i to the "sort" field.
func (suo *SiteUpdateOne) AddSort(i int32) *SiteUpdateOne {
	suo.mutation.AddSort(i)
	return suo
}

// SetStatus sets the "status" field.
func (suo *SiteUpdateOne) SetStatus(i int) *SiteUpdateOne {
	suo.mutation.ResetStatus()
	suo.mutation.SetStatus(i)
	return suo
}

// AddStatus adds i to the "status" field.
func (suo *SiteUpdateOne) AddStatus(i int) *SiteUpdateOne {
	suo.mutation.AddStatus(i)
	return suo
}

// SetName sets the "name" field.
func (suo *SiteUpdateOne) SetName(s string) *SiteUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetLink sets the "link" field.
func (suo *SiteUpdateOne) SetLink(s string) *SiteUpdateOne {
	suo.mutation.SetLink(s)
	return suo
}

// SetCategory sets the "category" field.
func (suo *SiteUpdateOne) SetCategory(s string) *SiteUpdateOne {
	suo.mutation.SetCategory(s)
	return suo
}

// Mutation returns the SiteMutation object of the builder.
func (suo *SiteUpdateOne) Mutation() *SiteMutation {
	return suo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SiteUpdateOne) Select(field string, fields ...string) *SiteUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Site entity.
func (suo *SiteUpdateOne) Save(ctx context.Context) (*Site, error) {
	var (
		err  error
		node *Site
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SiteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, suo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Site)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SiteMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SiteUpdateOne) SaveX(ctx context.Context) *Site {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SiteUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SiteUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SiteUpdateOne) sqlSave(ctx context.Context) (_node *Site, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   site.Table,
			Columns: site.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: site.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Site.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, site.FieldID)
		for _, f := range fields {
			if !site.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != site.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Sort(); ok {
		_spec.SetField(site.FieldSort, field.TypeInt32, value)
	}
	if value, ok := suo.mutation.AddedSort(); ok {
		_spec.AddField(site.FieldSort, field.TypeInt32, value)
	}
	if value, ok := suo.mutation.Status(); ok {
		_spec.SetField(site.FieldStatus, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedStatus(); ok {
		_spec.AddField(site.FieldStatus, field.TypeInt, value)
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(site.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Link(); ok {
		_spec.SetField(site.FieldLink, field.TypeString, value)
	}
	if value, ok := suo.mutation.Category(); ok {
		_spec.SetField(site.FieldCategory, field.TypeString, value)
	}
	_node = &Site{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
