// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Banner is the predicate function for banner builders.
type Banner func(*sql.Selector)

// Plan is the predicate function for plan builders.
type Plan func(*sql.Selector)

// PlanCategory is the predicate function for plancategory builders.
type PlanCategory func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// ProductCategory is the predicate function for productcategory builders.
type ProductCategory func(*sql.Selector)

// Site is the predicate function for site builders.
type Site func(*sql.Selector)
