// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: homepage/v1/homepage.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 为某个枚举单独设置错误码
	ErrorReason_USER_NOT_FOUND  ErrorReason = 0
	ErrorReason_CONTENT_MISSING ErrorReason = 1
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "USER_NOT_FOUND",
		1: "CONTENT_MISSING",
	}
	ErrorReason_value = map[string]int32{
		"USER_NOT_FOUND":  0,
		"CONTENT_MISSING": 1,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_homepage_v1_homepage_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_homepage_v1_homepage_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{0}
}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data    *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{0}
}

func (x *Reply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Reply) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetHomepageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHomepageRequest) Reset() {
	*x = GetHomepageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHomepageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomepageRequest) ProtoMessage() {}

func (x *GetHomepageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomepageRequest.ProtoReflect.Descriptor instead.
func (*GetHomepageRequest) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{1}
}

type GetHomepageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data    *Data  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetHomepageReply) Reset() {
	*x = GetHomepageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHomepageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomepageReply) ProtoMessage() {}

func (x *GetHomepageReply) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomepageReply.ProtoReflect.Descriptor instead.
func (*GetHomepageReply) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{2}
}

func (x *GetHomepageReply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetHomepageReply) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetHomepageReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetHomepageProRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHomepageProRequest) Reset() {
	*x = GetHomepageProRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHomepageProRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomepageProRequest) ProtoMessage() {}

func (x *GetHomepageProRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomepageProRequest.ProtoReflect.Descriptor instead.
func (*GetHomepageProRequest) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{3}
}

type GetHomepageProReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data    *DataPro `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetHomepageProReply) Reset() {
	*x = GetHomepageProReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHomepageProReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomepageProReply) ProtoMessage() {}

func (x *GetHomepageProReply) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomepageProReply.ProtoReflect.Descriptor instead.
func (*GetHomepageProReply) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{4}
}

func (x *GetHomepageProReply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetHomepageProReply) GetData() *DataPro {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetHomepageProReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSiteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSiteReq) Reset() {
	*x = GetSiteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSiteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteReq) ProtoMessage() {}

func (x *GetSiteReq) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteReq.ProtoReflect.Descriptor instead.
func (*GetSiteReq) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{5}
}

type GetSiteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data    []*Category `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Message string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetSiteReply) Reset() {
	*x = GetSiteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSiteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteReply) ProtoMessage() {}

func (x *GetSiteReply) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteReply.ProtoReflect.Descriptor instead.
func (*GetSiteReply) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{6}
}

func (x *GetSiteReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSiteReply) GetData() []*Category {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetSiteReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSearchProRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Keyword string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Type    int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetSearchProRequest) Reset() {
	*x = GetSearchProRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSearchProRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchProRequest) ProtoMessage() {}

func (x *GetSearchProRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchProRequest.ProtoReflect.Descriptor instead.
func (*GetSearchProRequest) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{7}
}

func (x *GetSearchProRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetSearchProRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetSearchProRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetSearchProReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data    *Search `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message string  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetSearchProReply) Reset() {
	*x = GetSearchProReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSearchProReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchProReply) ProtoMessage() {}

func (x *GetSearchProReply) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchProReply.ProtoReflect.Descriptor instead.
func (*GetSearchProReply) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{8}
}

func (x *GetSearchProReply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSearchProReply) GetData() *Search {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetSearchProReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ListSearchRequest) Reset() {
	*x = ListSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSearchRequest) ProtoMessage() {}

func (x *ListSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSearchRequest.ProtoReflect.Descriptor instead.
func (*ListSearchRequest) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{9}
}

func (x *ListSearchRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ListSearchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data    *Datasearch `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ListSearchReply) Reset() {
	*x = ListSearchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSearchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSearchReply) ProtoMessage() {}

func (x *ListSearchReply) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSearchReply.ProtoReflect.Descriptor instead.
func (*ListSearchReply) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{10}
}

func (x *ListSearchReply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListSearchReply) GetData() *Datasearch {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListSearchReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Keyword string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Type    int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *SetSearchRequest) Reset() {
	*x = SetSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSearchRequest) ProtoMessage() {}

func (x *SetSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSearchRequest.ProtoReflect.Descriptor instead.
func (*SetSearchRequest) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{11}
}

func (x *SetSearchRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetSearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SetSearchRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type SetSearchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data    string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SetSearchReply) Reset() {
	*x = SetSearchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSearchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSearchReply) ProtoMessage() {}

func (x *SetSearchReply) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSearchReply.ProtoReflect.Descriptor instead.
func (*SetSearchReply) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{12}
}

func (x *SetSearchReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetSearchReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SetSearchReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DelSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Isdelete int32 `protobuf:"varint,1,opt,name=isdelete,proto3" json:"isdelete,omitempty"`
}

func (x *DelSearchRequest) Reset() {
	*x = DelSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSearchRequest) ProtoMessage() {}

func (x *DelSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSearchRequest.ProtoReflect.Descriptor instead.
func (*DelSearchRequest) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{13}
}

func (x *DelSearchRequest) GetIsdelete() int32 {
	if x != nil {
		return x.Isdelete
	}
	return 0
}

type DelSearchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DelSearchReply) Reset() {
	*x = DelSearchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelSearchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSearchReply) ProtoMessage() {}

func (x *DelSearchReply) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSearchReply.ProtoReflect.Descriptor instead.
func (*DelSearchReply) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{14}
}

func (x *DelSearchReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DelSearchReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Datasearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecentSearch  []*Search `protobuf:"bytes,1,rep,name=recentSearch,proto3" json:"recentSearch,omitempty"`
	HistorySearch []*Search `protobuf:"bytes,2,rep,name=historySearch,proto3" json:"historySearch,omitempty"`
}

func (x *Datasearch) Reset() {
	*x = Datasearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Datasearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datasearch) ProtoMessage() {}

func (x *Datasearch) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datasearch.ProtoReflect.Descriptor instead.
func (*Datasearch) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{15}
}

func (x *Datasearch) GetRecentSearch() []*Search {
	if x != nil {
		return x.RecentSearch
	}
	return nil
}

func (x *Datasearch) GetHistorySearch() []*Search {
	if x != nil {
		return x.HistorySearch
	}
	return nil
}

type Search struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type    int32  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Keyword string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *Search) Reset() {
	*x = Search{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{16}
}

func (x *Search) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Search) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Search) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type DataPro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proc []*ProCategory `protobuf:"bytes,1,rep,name=proc,proto3" json:"proc,omitempty"`
	Pro  []*Search      `protobuf:"bytes,2,rep,name=pro,proto3" json:"pro,omitempty"`
}

func (x *DataPro) Reset() {
	*x = DataPro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPro) ProtoMessage() {}

func (x *DataPro) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPro.ProtoReflect.Descriptor instead.
func (*DataPro) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{17}
}

func (x *DataPro) GetProc() []*ProCategory {
	if x != nil {
		return x.Proc
	}
	return nil
}

func (x *DataPro) GetPro() []*Search {
	if x != nil {
		return x.Pro
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Banner   []*Banner       `protobuf:"bytes,1,rep,name=banner,proto3" json:"banner,omitempty"`
	Product  []*Product      `protobuf:"bytes,2,rep,name=product,proto3" json:"product,omitempty"`
	PlanCate []*PlanCategory `protobuf:"bytes,3,rep,name=planCate,proto3" json:"planCate,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{18}
}

func (x *Data) GetBanner() []*Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *Data) GetProduct() []*Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *Data) GetPlanCate() []*PlanCategory {
	if x != nil {
		return x.PlanCate
	}
	return nil
}

type Banner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type   string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Url    string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	LinkId string `protobuf:"bytes,5,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Sort   int32  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (x *Banner) Reset() {
	*x = Banner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{19}
}

func (x *Banner) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Banner) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Banner) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Banner) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Banner) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *Banner) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type ProCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid      int32     `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Name     string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Children []*Level2 `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *ProCategory) Reset() {
	*x = ProCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProCategory) ProtoMessage() {}

func (x *ProCategory) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProCategory.ProtoReflect.Descriptor instead.
func (*ProCategory) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{20}
}

func (x *ProCategory) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProCategory) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProCategory) GetChildren() []*Level2 {
	if x != nil {
		return x.Children
	}
	return nil
}

type Level2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid      int32      `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Name     string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Children []*Product `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *Level2) Reset() {
	*x = Level2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Level2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level2) ProtoMessage() {}

func (x *Level2) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level2.ProtoReflect.Descriptor instead.
func (*Level2) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{21}
}

func (x *Level2) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Level2) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Level2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Level2) GetChildren() []*Product {
	if x != nil {
		return x.Children
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid     int32  `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	History int32  `protobuf:"varint,3,opt,name=history,proto3" json:"history,omitempty"`
	Cname   string `protobuf:"bytes,4,opt,name=cname,proto3" json:"cname,omitempty"`
	Name    string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{22}
}

func (x *Product) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *Product) GetHistory() int32 {
	if x != nil {
		return x.History
	}
	return 0
}

func (x *Product) GetCname() string {
	if x != nil {
		return x.Cname
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PlanCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sort    int32   `protobuf:"varint,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Name    string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Bucket  *string `protobuf:"bytes,4,opt,name=bucket,proto3,oneof" json:"bucket,omitempty"`
	Url     string  `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Content string  `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *PlanCategory) Reset() {
	*x = PlanCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlanCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanCategory) ProtoMessage() {}

func (x *PlanCategory) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanCategory.ProtoReflect.Descriptor instead.
func (*PlanCategory) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{23}
}

func (x *PlanCategory) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlanCategory) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PlanCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlanCategory) GetBucket() string {
	if x != nil && x.Bucket != nil {
		return *x.Bucket
	}
	return ""
}

func (x *PlanCategory) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PlanCategory) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string           `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Site     []*Category_Site `protobuf:"bytes,2,rep,name=site,proto3" json:"site,omitempty"`
}

func (x *Category) Reset() {
	*x = Category{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{24}
}

func (x *Category) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Category) GetSite() []*Category_Site {
	if x != nil {
		return x.Site
	}
	return nil
}

type Category_Site struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Link string `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *Category_Site) Reset() {
	*x = Category_Site{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homepage_v1_homepage_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category_Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category_Site) ProtoMessage() {}

func (x *Category_Site) ProtoReflect() protoreflect.Message {
	mi := &file_homepage_v1_homepage_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category_Site.ProtoReflect.Descriptor instead.
func (*Category_Site) Descriptor() ([]byte, []int) {
	return file_homepage_v1_homepage_proto_rawDescGZIP(), []int{24, 0}
}

func (x *Category_Site) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category_Site) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category_Site) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_homepage_v1_homepage_proto protoreflect.FileDescriptor

var file_homepage_v1_homepage_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x6f,
	0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x70,
	0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62,
	0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x48,
	0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x6d, 0x65,
	0x70, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x71,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f,
	0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x72,
	0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x22,
	0x6b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x53, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x6e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x72,
	0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68,
	0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x27, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x70, 0x0a, 0x0f, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x2f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x50, 0x0a, 0x10,
	0x53, 0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x52,
	0x0a, 0x0e, 0x53, 0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x2e, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x73, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x22, 0x3e, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x12, 0x3b, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f,
	0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x3d,
	0x0a, 0x0d, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65,
	0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x0d,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x22, 0x46, 0x0a,
	0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x66, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f,
	0x12, 0x30, 0x0a, 0x04, 0x70, 0x72, 0x6f, 0x63, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x04, 0x70, 0x72,
	0x6f, 0x63, 0x12, 0x29, 0x0a, 0x03, 0x70, 0x72, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x03, 0x70, 0x72, 0x6f, 0x22, 0xa6, 0x01,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d,
	0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52,
	0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68,
	0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x39, 0x0a, 0x08, 0x70,
	0x6c, 0x61, 0x6e, 0x43, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6c, 0x61, 0x6e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x6e, 0x43, 0x61, 0x74, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x06, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x17, 0x0a,
	0x07, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x78, 0x0a, 0x0b, 0x50, 0x72,
	0x6f, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x33, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x32, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c,
	0x64, 0x72, 0x65, 0x6e, 0x22, 0x74, 0x0a, 0x06, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x32, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d,
	0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x22, 0x89, 0x01, 0x0a, 0x07, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x9a, 0x01, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x6e, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x22, 0x9a, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x32, 0x0a, 0x04,
	0x73, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65,
	0x1a, 0x3e, 0x0a, 0x04, 0x53, 0x69, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b,
	0x2a, 0x48, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e,
	0x44, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45, 0x94, 0x03, 0x12, 0x19, 0x0a, 0x0f, 0x43, 0x4f, 0x4e,
	0x54, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x1a, 0x04,
	0xa8, 0x45, 0x90, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x32, 0xdc, 0x05, 0x0a, 0x08, 0x48,
	0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x12, 0x6e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x48, 0x6f,
	0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d,
	0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x6d, 0x65,
	0x70, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x12, 0x1a, 0x2f, 0x67, 0x72,
	0x65, 0x65, 0x79, 0x75, 0x6e, 0x2f, 0x66, 0x6d, 0x7a, 0x2d, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x68,
	0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x12, 0x86, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48,
	0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x48, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x34, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x2e, 0x12, 0x2c, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x79, 0x75, 0x6e, 0x2f, 0x66, 0x6d, 0x7a,
	0x2d, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x61, 0x6e, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53, 0x69, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68,
	0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x67, 0x72, 0x65, 0x65, 0x79, 0x75,
	0x6e, 0x2f, 0x66, 0x6d, 0x7a, 0x2d, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x73, 0x69, 0x74, 0x65, 0x12,
	0x7e, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x22, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x34, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x2e, 0x12, 0x2c, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x79, 0x75, 0x6e, 0x2f, 0x66, 0x6d, 0x7a, 0x2d,
	0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x6c, 0x69,
	0x73, 0x74, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x7b, 0x74, 0x79, 0x70, 0x65, 0x7d, 0x12,
	0x77, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x21, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x29, 0x22,
	0x24, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x79, 0x75, 0x6e, 0x2f, 0x66, 0x6d, 0x7a, 0x2d, 0x68, 0x6f,
	0x6d, 0x65, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2f, 0x73, 0x65, 0x74, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x3a, 0x01, 0x2a, 0x12, 0x7f, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x6f, 0x6d, 0x65,
	0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68,
	0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x37, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x31, 0x2a, 0x2f, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x79,
	0x75, 0x6e, 0x2f, 0x66, 0x6d, 0x7a, 0x2d, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x68, 0x6f, 0x6d, 0x65,
	0x70, 0x61, 0x67, 0x65, 0x2f, 0x44, 0x65, 0x6c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x7b,
	0x69, 0x73, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x7d, 0x42, 0x2f, 0x0a, 0x0f, 0x61, 0x70, 0x69,
	0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1a,
	0x67, 0x79, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x6f, 0x6d, 0x65,
	0x70, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_homepage_v1_homepage_proto_rawDescOnce sync.Once
	file_homepage_v1_homepage_proto_rawDescData = file_homepage_v1_homepage_proto_rawDesc
)

func file_homepage_v1_homepage_proto_rawDescGZIP() []byte {
	file_homepage_v1_homepage_proto_rawDescOnce.Do(func() {
		file_homepage_v1_homepage_proto_rawDescData = protoimpl.X.CompressGZIP(file_homepage_v1_homepage_proto_rawDescData)
	})
	return file_homepage_v1_homepage_proto_rawDescData
}

var file_homepage_v1_homepage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_homepage_v1_homepage_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_homepage_v1_homepage_proto_goTypes = []interface{}{
	(ErrorReason)(0),              // 0: api.homepage.v1.ErrorReason
	(*Reply)(nil),                 // 1: api.homepage.v1.Reply
	(*GetHomepageRequest)(nil),    // 2: api.homepage.v1.GetHomepageRequest
	(*GetHomepageReply)(nil),      // 3: api.homepage.v1.GetHomepageReply
	(*GetHomepageProRequest)(nil), // 4: api.homepage.v1.GetHomepageProRequest
	(*GetHomepageProReply)(nil),   // 5: api.homepage.v1.GetHomepageProReply
	(*GetSiteReq)(nil),            // 6: api.homepage.v1.GetSiteReq
	(*GetSiteReply)(nil),          // 7: api.homepage.v1.GetSiteReply
	(*GetSearchProRequest)(nil),   // 8: api.homepage.v1.GetSearchProRequest
	(*GetSearchProReply)(nil),     // 9: api.homepage.v1.GetSearchProReply
	(*ListSearchRequest)(nil),     // 10: api.homepage.v1.ListSearchRequest
	(*ListSearchReply)(nil),       // 11: api.homepage.v1.ListSearchReply
	(*SetSearchRequest)(nil),      // 12: api.homepage.v1.SetSearchRequest
	(*SetSearchReply)(nil),        // 13: api.homepage.v1.SetSearchReply
	(*DelSearchRequest)(nil),      // 14: api.homepage.v1.DelSearchRequest
	(*DelSearchReply)(nil),        // 15: api.homepage.v1.DelSearchReply
	(*Datasearch)(nil),            // 16: api.homepage.v1.Datasearch
	(*Search)(nil),                // 17: api.homepage.v1.Search
	(*DataPro)(nil),               // 18: api.homepage.v1.DataPro
	(*Data)(nil),                  // 19: api.homepage.v1.Data
	(*Banner)(nil),                // 20: api.homepage.v1.Banner
	(*ProCategory)(nil),           // 21: api.homepage.v1.ProCategory
	(*Level2)(nil),                // 22: api.homepage.v1.Level2
	(*Product)(nil),               // 23: api.homepage.v1.Product
	(*PlanCategory)(nil),          // 24: api.homepage.v1.PlanCategory
	(*Category)(nil),              // 25: api.homepage.v1.Category
	(*Category_Site)(nil),         // 26: api.homepage.v1.Category.Site
	(*structpb.Struct)(nil),       // 27: google.protobuf.Struct
}
var file_homepage_v1_homepage_proto_depIdxs = []int32{
	27, // 0: api.homepage.v1.Reply.data:type_name -> google.protobuf.Struct
	19, // 1: api.homepage.v1.GetHomepageReply.data:type_name -> api.homepage.v1.Data
	18, // 2: api.homepage.v1.GetHomepageProReply.data:type_name -> api.homepage.v1.DataPro
	25, // 3: api.homepage.v1.GetSiteReply.data:type_name -> api.homepage.v1.Category
	17, // 4: api.homepage.v1.GetSearchProReply.data:type_name -> api.homepage.v1.Search
	16, // 5: api.homepage.v1.ListSearchReply.data:type_name -> api.homepage.v1.Datasearch
	17, // 6: api.homepage.v1.Datasearch.recentSearch:type_name -> api.homepage.v1.Search
	17, // 7: api.homepage.v1.Datasearch.historySearch:type_name -> api.homepage.v1.Search
	21, // 8: api.homepage.v1.DataPro.proc:type_name -> api.homepage.v1.ProCategory
	17, // 9: api.homepage.v1.DataPro.pro:type_name -> api.homepage.v1.Search
	20, // 10: api.homepage.v1.Data.banner:type_name -> api.homepage.v1.Banner
	23, // 11: api.homepage.v1.Data.product:type_name -> api.homepage.v1.Product
	24, // 12: api.homepage.v1.Data.planCate:type_name -> api.homepage.v1.PlanCategory
	22, // 13: api.homepage.v1.ProCategory.children:type_name -> api.homepage.v1.Level2
	23, // 14: api.homepage.v1.Level2.children:type_name -> api.homepage.v1.Product
	26, // 15: api.homepage.v1.Category.site:type_name -> api.homepage.v1.Category.Site
	2,  // 16: api.homepage.v1.Homepage.GetHomepage:input_type -> api.homepage.v1.GetHomepageRequest
	4,  // 17: api.homepage.v1.Homepage.GetHomepagePro:input_type -> api.homepage.v1.GetHomepageProRequest
	6,  // 18: api.homepage.v1.Homepage.GetSite:input_type -> api.homepage.v1.GetSiteReq
	10, // 19: api.homepage.v1.Homepage.ListSearch:input_type -> api.homepage.v1.ListSearchRequest
	12, // 20: api.homepage.v1.Homepage.SetSearch:input_type -> api.homepage.v1.SetSearchRequest
	14, // 21: api.homepage.v1.Homepage.DelSearch:input_type -> api.homepage.v1.DelSearchRequest
	1,  // 22: api.homepage.v1.Homepage.GetHomepage:output_type -> api.homepage.v1.Reply
	1,  // 23: api.homepage.v1.Homepage.GetHomepagePro:output_type -> api.homepage.v1.Reply
	1,  // 24: api.homepage.v1.Homepage.GetSite:output_type -> api.homepage.v1.Reply
	1,  // 25: api.homepage.v1.Homepage.ListSearch:output_type -> api.homepage.v1.Reply
	1,  // 26: api.homepage.v1.Homepage.SetSearch:output_type -> api.homepage.v1.Reply
	1,  // 27: api.homepage.v1.Homepage.DelSearch:output_type -> api.homepage.v1.Reply
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_homepage_v1_homepage_proto_init() }
func file_homepage_v1_homepage_proto_init() {
	if File_homepage_v1_homepage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_homepage_v1_homepage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHomepageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHomepageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHomepageProRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHomepageProReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSiteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSiteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSearchProRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSearchProReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSearchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSearchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelSearchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Datasearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Search); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataPro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Level2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlanCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homepage_v1_homepage_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category_Site); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_homepage_v1_homepage_proto_msgTypes[23].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_homepage_v1_homepage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_homepage_v1_homepage_proto_goTypes,
		DependencyIndexes: file_homepage_v1_homepage_proto_depIdxs,
		EnumInfos:         file_homepage_v1_homepage_proto_enumTypes,
		MessageInfos:      file_homepage_v1_homepage_proto_msgTypes,
	}.Build()
	File_homepage_v1_homepage_proto = out.File
	file_homepage_v1_homepage_proto_rawDesc = nil
	file_homepage_v1_homepage_proto_goTypes = nil
	file_homepage_v1_homepage_proto_depIdxs = nil
}
