// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: api/plan/v1/detailsOfPlan.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data    *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_api_plan_v1_detailsOfPlan_proto_rawDescGZIP(), []int{0}
}

func (x *Reply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Reply) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid    int32  `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Listid *int32 `protobuf:"varint,2,opt,name=listid,proto3,oneof" json:"listid,omitempty"`
	Id     *int32 `protobuf:"varint,3,opt,name=id,proto3,oneof" json:"id,omitempty"`
}

func (x *GetPlanRequest) Reset() {
	*x = GetPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanRequest) ProtoMessage() {}

func (x *GetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanRequest.ProtoReflect.Descriptor instead.
func (*GetPlanRequest) Descriptor() ([]byte, []int) {
	return file_api_plan_v1_detailsOfPlan_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlanRequest) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *GetPlanRequest) GetListid() int32 {
	if x != nil && x.Listid != nil {
		return *x.Listid
	}
	return 0
}

func (x *GetPlanRequest) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type GetPlanReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data    *Data  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetPlanReply) Reset() {
	*x = GetPlanReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanReply) ProtoMessage() {}

func (x *GetPlanReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanReply.ProtoReflect.Descriptor instead.
func (*GetPlanReply) Descriptor() ([]byte, []int) {
	return file_api_plan_v1_detailsOfPlan_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlanReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPlanReply) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetPlanReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid int32 `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *ListPlanRequest) Reset() {
	*x = ListPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlanRequest) ProtoMessage() {}

func (x *ListPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlanRequest.ProtoReflect.Descriptor instead.
func (*ListPlanRequest) Descriptor() ([]byte, []int) {
	return file_api_plan_v1_detailsOfPlan_proto_rawDescGZIP(), []int{3}
}

func (x *ListPlanRequest) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plan      *Plan        `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	Cap       int32        `protobuf:"varint,2,opt,name=cap,proto3" json:"cap,omitempty"`
	Parent    *Data_Parent `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Recommend []*Plan      `protobuf:"bytes,4,rep,name=recommend,proto3" json:"recommend,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_api_plan_v1_detailsOfPlan_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *Data) GetCap() int32 {
	if x != nil {
		return x.Cap
	}
	return 0
}

func (x *Data) GetParent() *Data_Parent {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Data) GetRecommend() []*Plan {
	if x != nil {
		return x.Recommend
	}
	return nil
}

type Plan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid    int32  `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Listid int32  `protobuf:"varint,3,opt,name=listid,proto3" json:"listid,omitempty"`
	Cname  string `protobuf:"bytes,4,opt,name=cname,proto3" json:"cname,omitempty"`
	Name   string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Url    string `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Utime  string `protobuf:"bytes,7,opt,name=utime,proto3" json:"utime,omitempty"`
}

func (x *Plan) Reset() {
	*x = Plan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_api_plan_v1_detailsOfPlan_proto_rawDescGZIP(), []int{5}
}

func (x *Plan) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Plan) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *Plan) GetListid() int32 {
	if x != nil {
		return x.Listid
	}
	return 0
}

func (x *Plan) GetCname() string {
	if x != nil {
		return x.Cname
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Plan) GetUtime() string {
	if x != nil {
		return x.Utime
	}
	return ""
}

type Data_Parent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CName string  `protobuf:"bytes,1,opt,name=CName,proto3" json:"CName,omitempty"`
	Plan  []*Plan `protobuf:"bytes,2,rep,name=plan,proto3" json:"plan,omitempty"`
}

func (x *Data_Parent) Reset() {
	*x = Data_Parent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data_Parent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Parent) ProtoMessage() {}

func (x *Data_Parent) ProtoReflect() protoreflect.Message {
	mi := &file_api_plan_v1_detailsOfPlan_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Parent.ProtoReflect.Descriptor instead.
func (*Data_Parent) Descriptor() ([]byte, []int) {
	return file_api_plan_v1_detailsOfPlan_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Data_Parent) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

func (x *Data_Parent) GetPlan() []*Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

var File_api_plan_v1_detailsOfPlan_proto protoreflect.FileDescriptor

var file_api_plan_v1_detailsOfPlan_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66, 0x50, 0x6c, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x14, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66,
	0x50, 0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x66, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x6c,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x64, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x22,
	0x6c, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f,
	0x66, 0x50, 0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x23, 0x0a,
	0x0f, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63,
	0x69, 0x64, 0x22, 0x8d, 0x02, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x04, 0x70,
	0x6c, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66, 0x50, 0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x61, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x61, 0x70, 0x12, 0x39, 0x0a,
	0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66, 0x50, 0x6c, 0x61,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66, 0x50, 0x6c, 0x61, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x64, 0x1a, 0x4e, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66,
	0x50, 0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x04, 0x70, 0x6c,
	0x61, 0x6e, 0x22, 0x92, 0x01, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x75, 0x74, 0x69, 0x6d, 0x65, 0x32, 0x84, 0x02, 0x0a, 0x0d, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x4f, 0x66, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x77, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x6e, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x4f, 0x66, 0x50, 0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66, 0x50, 0x6c, 0x61, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x22,
	0x1e, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x79, 0x75, 0x6e, 0x2f, 0x66, 0x6d, 0x7a, 0x2d, 0x68, 0x6f,
	0x6d, 0x65, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x2f, 0x67, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x3a,
	0x01, 0x2a, 0x12, 0x7a, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x25,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66, 0x50, 0x6c,
	0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x4f, 0x66, 0x50, 0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24, 0x22, 0x1f, 0x2f, 0x67, 0x72, 0x65,
	0x65, 0x79, 0x75, 0x6e, 0x2f, 0x66, 0x6d, 0x7a, 0x2d, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x70, 0x6c,
	0x61, 0x6e, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x3a, 0x01, 0x2a, 0x42, 0x39,
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66, 0x50,
	0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1f, 0x67, 0x79, 0x5f, 0x68, 0x6f, 0x6d,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4f, 0x66, 0x50,
	0x6c, 0x61, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_plan_v1_detailsOfPlan_proto_rawDescOnce sync.Once
	file_api_plan_v1_detailsOfPlan_proto_rawDescData = file_api_plan_v1_detailsOfPlan_proto_rawDesc
)

func file_api_plan_v1_detailsOfPlan_proto_rawDescGZIP() []byte {
	file_api_plan_v1_detailsOfPlan_proto_rawDescOnce.Do(func() {
		file_api_plan_v1_detailsOfPlan_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_plan_v1_detailsOfPlan_proto_rawDescData)
	})
	return file_api_plan_v1_detailsOfPlan_proto_rawDescData
}

var file_api_plan_v1_detailsOfPlan_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_plan_v1_detailsOfPlan_proto_goTypes = []interface{}{
	(*Reply)(nil),           // 0: api.detailsOfPlan.v1.Reply
	(*GetPlanRequest)(nil),  // 1: api.detailsOfPlan.v1.GetPlanRequest
	(*GetPlanReply)(nil),    // 2: api.detailsOfPlan.v1.GetPlanReply
	(*ListPlanRequest)(nil), // 3: api.detailsOfPlan.v1.ListPlanRequest
	(*Data)(nil),            // 4: api.detailsOfPlan.v1.Data
	(*Plan)(nil),            // 5: api.detailsOfPlan.v1.Plan
	(*Data_Parent)(nil),     // 6: api.detailsOfPlan.v1.Data.Parent
	(*structpb.Struct)(nil), // 7: google.protobuf.Struct
}
var file_api_plan_v1_detailsOfPlan_proto_depIdxs = []int32{
	7, // 0: api.detailsOfPlan.v1.Reply.data:type_name -> google.protobuf.Struct
	4, // 1: api.detailsOfPlan.v1.GetPlanReply.data:type_name -> api.detailsOfPlan.v1.Data
	5, // 2: api.detailsOfPlan.v1.Data.plan:type_name -> api.detailsOfPlan.v1.Plan
	6, // 3: api.detailsOfPlan.v1.Data.parent:type_name -> api.detailsOfPlan.v1.Data.Parent
	5, // 4: api.detailsOfPlan.v1.Data.recommend:type_name -> api.detailsOfPlan.v1.Plan
	5, // 5: api.detailsOfPlan.v1.Data.Parent.plan:type_name -> api.detailsOfPlan.v1.Plan
	1, // 6: api.detailsOfPlan.v1.DetailsOfPlan.GetPlan:input_type -> api.detailsOfPlan.v1.GetPlanRequest
	3, // 7: api.detailsOfPlan.v1.DetailsOfPlan.ListPlan:input_type -> api.detailsOfPlan.v1.ListPlanRequest
	0, // 8: api.detailsOfPlan.v1.DetailsOfPlan.GetPlan:output_type -> api.detailsOfPlan.v1.Reply
	0, // 9: api.detailsOfPlan.v1.DetailsOfPlan.ListPlan:output_type -> api.detailsOfPlan.v1.Reply
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_plan_v1_detailsOfPlan_proto_init() }
func file_api_plan_v1_detailsOfPlan_proto_init() {
	if File_api_plan_v1_detailsOfPlan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_plan_v1_detailsOfPlan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_plan_v1_detailsOfPlan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_plan_v1_detailsOfPlan_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlanReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_plan_v1_detailsOfPlan_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_plan_v1_detailsOfPlan_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_plan_v1_detailsOfPlan_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_plan_v1_detailsOfPlan_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data_Parent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_plan_v1_detailsOfPlan_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_plan_v1_detailsOfPlan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_plan_v1_detailsOfPlan_proto_goTypes,
		DependencyIndexes: file_api_plan_v1_detailsOfPlan_proto_depIdxs,
		MessageInfos:      file_api_plan_v1_detailsOfPlan_proto_msgTypes,
	}.Build()
	File_api_plan_v1_detailsOfPlan_proto = out.File
	file_api_plan_v1_detailsOfPlan_proto_rawDesc = nil
	file_api_plan_v1_detailsOfPlan_proto_goTypes = nil
	file_api_plan_v1_detailsOfPlan_proto_depIdxs = nil
}
