// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gy_home/internal/biz"
	"gy_home/internal/conf"
	"gy_home/internal/data"
	"gy_home/internal/server"
	"gy_home/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewEntClient(confData, logger)
	dataData, cleanup, err := data.NewData(confData, logger, client)
	if err != nil {
		return nil, nil, err
	}
	homepageRepo := data.NewHomepageRepo(dataData, logger)
	homepageUsecase := biz.NewHomepageUsecase(homepageRepo, logger)
	homepageService := service.NewHomepageService(homepageUsecase, logger)
	planRepo := data.NewPlanRepo(dataData, logger)
	planUseCase := biz.NewPlanUseCase(planRepo, logger)
	detailsOfPlanService := service.NewDetailsOfPlanService(planUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, homepageService, detailsOfPlanService, logger)
	httpServer := server.NewHTTPServer(confServer, logger, homepageService, detailsOfPlanService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
