// Code generated by ent, DO NOT EDIT.

package banner

const (
	// Label holds the string label denoting the banner type in the database.
	Label = "banner"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldLinkID holds the string denoting the link_id field in the database.
	FieldLinkID = "link_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the banner in the database.
	Table = "banner"
)

// Columns holds all SQL columns for banner fields.
var Columns = []string{
	FieldID,
	FieldURL,
	FieldSort,
	FieldTitle,
	FieldType,
	FieldLinkID,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultURL holds the default value on creation for the "url" field.
	DefaultURL string
	// DefaultSort holds the default value on creation for the "sort" field.
	DefaultSort int32
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// DefaultLinkID holds the default value on creation for the "link_id" field.
	DefaultLinkID string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID int32
)
