// Code generated by ent, DO NOT EDIT.

package product

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRecommend holds the string denoting the recommend field in the database.
	FieldRecommend = "recommend"
	// FieldHistory holds the string denoting the history field in the database.
	FieldHistory = "history"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldCategoryName holds the string denoting the category_name field in the database.
	FieldCategoryName = "category_name"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldUtime holds the string denoting the utime field in the database.
	FieldUtime = "utime"
	// FieldServiceLink holds the string denoting the service_link field in the database.
	FieldServiceLink = "service_link"
	// FieldApplyLink holds the string denoting the apply_link field in the database.
	FieldApplyLink = "apply_link"
	// FieldJSON holds the string denoting the json field in the database.
	FieldJSON = "json"
	// EdgeParentID holds the string denoting the parent_id edge name in mutations.
	EdgeParentID = "parent_id"
	// Table holds the table name of the product in the database.
	Table = "product"
	// ParentIDTable is the table that holds the parent_id relation/edge.
	ParentIDTable = "product"
	// ParentIDInverseTable is the table name for the ProductCategory entity.
	// It exists in this package in order to avoid circular dependency with the "productcategory" package.
	ParentIDInverseTable = "product_category"
	// ParentIDColumn is the table column denoting the parent_id relation/edge.
	ParentIDColumn = "category_id"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldRecommend,
	FieldHistory,
	FieldCategoryID,
	FieldCategoryName,
	FieldName,
	FieldContent,
	FieldUtime,
	FieldServiceLink,
	FieldApplyLink,
	FieldJSON,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int
	// DefaultRecommend holds the default value on creation for the "recommend" field.
	DefaultRecommend int
	// DefaultHistory holds the default value on creation for the "history" field.
	DefaultHistory int32
	// DefaultCategoryID holds the default value on creation for the "category_id" field.
	DefaultCategoryID int32
	// DefaultCategoryName holds the default value on creation for the "category_name" field.
	DefaultCategoryName string
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultContent holds the default value on creation for the "content" field.
	DefaultContent string
	// DefaultServiceLink holds the default value on creation for the "service_link" field.
	DefaultServiceLink string
	// DefaultApplyLink holds the default value on creation for the "apply_link" field.
	DefaultApplyLink string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID int32
)
